{"name": "test_login[test_data3]", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778", "trace": "request = <SubRequest 'driver' for <Function test_login[test_data3]>>\n\n    @pytest.fixture\n    def driver(request):\n        config = ConfigReader()\n        browser = config.get_browser_type()\n>       driver = DriverFactory.create_driver(browser)\n\nconftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities\\driver_factory.py:17: in create_driver\n    ChromeDriverManager().install(),\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\chrome.py:32: in install\n    driver_path = self._get_driver_path(self.driver)\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\manager.py:23: in _get_driver_path\n    driver_version = driver.get_version()\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py:41: in get_version\n    return self.get_latest_release_version()\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py:74: in get_latest_release_version\n    validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    def validate_response(resp):\n        if resp.status_code == 404:\n>           raise ValueError(\"There is no such driver by url {}\".format(resp.url))\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778\n\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\utils.py:80: ValueError"}, "attachments": [{"name": "log", "source": "9b806644-9325-44d3-833f-b242b4643872-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "66709466-5c0d-4834-a0f2-033a01355ace-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_data", "value": "{'username': 'demo@opencart.com', 'password': '', 'expected_result': 'failure', 'error_message': 'Warning: Please enter your password '}"}], "start": 1735548355210, "stop": 1735548355210, "uuid": "46522e58-273a-4e0a-abfc-3ab07a4563e9", "historyId": "18be242c8c6851a06444f976980df173", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "로그인"}, {"name": "story", "value": "데이터 기반 로그인 테스트"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "JiHee"}, {"name": "thread", "value": "35048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}