{"name": "test_login[test_data0]", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778", "trace": "request = <SubRequest 'driver' for <Function test_login[test_data0]>>\n\n    @pytest.fixture\n    def driver(request):\n        config = ConfigReader()\n        browser = config.get_browser_type()\n>       driver = DriverFactory.create_driver(browser)\n\nconftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities\\driver_factory.py:17: in create_driver\n    ChromeDriverManager().install(),\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\chrome.py:32: in install\n    driver_path = self._get_driver_path(self.driver)\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\manager.py:23: in _get_driver_path\n    driver_version = driver.get_version()\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py:41: in get_version\n    return self.get_latest_release_version()\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py:74: in get_latest_release_version\n    validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    def validate_response(resp):\n        if resp.status_code == 404:\n>           raise ValueError(\"There is no such driver by url {}\".format(resp.url))\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778\n\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\utils.py:80: ValueError"}, "attachments": [{"name": "log", "source": "0caec850-daf3-4d27-94f1-7ae0020c5fca-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "52473cae-360f-48d1-af4d-ebb378e8b64d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_data", "value": "{'username': 'test123@opencart.com', 'password': 'test123', 'expected_result': 'success', 'error_message': ''}"}], "start": 1735548354299, "stop": 1735548354299, "uuid": "2cb599d3-d1bf-4627-a9cd-d3003c91a44a", "historyId": "83bbdac3a3c737e7b7c5ad083429e6de", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "로그인"}, {"name": "story", "value": "데이터 기반 로그인 테스트"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "JiHee"}, {"name": "thread", "value": "35048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}